"""add is_superadmin to users

Revision ID: 7b242403bdd0
Revises: 80947128071f
Create Date: 2026-03-12 18:30:58.540236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b242403bdd0'
down_revision = '80947128071f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_superadmin', sa.Boolean(), server_default='false', nullable=False))
        batch_op.create_index(batch_op.f('ix_users_is_superadmin'), ['is_superadmin'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_is_superadmin'))
        batch_op.drop_column('is_superadmin')

    # ### end Alembic commands ###
